### PR TITLE
articles/testing/contract-testing.md

### PR DESCRIPTION
**Pull request by rowa97**

### CODE REVIEW

**Comment by rossmcdonald** [comment]
@rowa97 Did you mean to create a PR for this?

**Comment by rowa97** [comment]
yeah, I should probably break them up, it's unfortunate because they all work well together, still considering it

**Comment by rossmcdonald** [comment]
@rowa97 I'm not sure I follow. There aren't any files in this PR except an empty one and `articles/testing/contract-testing.md` with a space removed.

https://github.com/stoplightio/docs/pull/148/files

**Comment by rossmcdonald** [comment]
@rowa97 This one has already been reviewed (through #155). Feel free to merge.

**Pull request merged**
