### PR TITLE
Add Spec Validation

### PR DESCRIPTION
**Pull request by rossmcdonald**
Please note that this article relies on the gif from #116, so that will need to be merged in order for the gif to display properly. I couldn't think of a better gif to use for file/spec validation so I used the same one for both, but let me know if I should create another one.

Fixes https://github.com/stoplightio/docs/issues/37

### CODE REVIEW

**Comment by rossmcdonald** [comment]
@rowa97 Regarding your feedback:

> gif could use a bit more

I updated the GIF via #116. Let me know if you think we should have different ones for each article. Unfortunately the only "real" validation we have is for OAS specs (the rest are syntax-only), so there's only so many ways to show validation issues on an OAS spec.

> this is where we have to get into the meat and cheese

I'm not sure I know how to go into more detail without going through the OAS spec, which is linked in the doc, but is waaaay too much information to cover for something like this.

> is there anything unique that we need to tell the users

Nothing that I'm aware of. The validation is actually pretty simple, the library we use just performs a check on the OAS file (based on the linked OAS specification) and returns a list of errors/warnings if there were any found.

> any limitations or strengths

None that I'm aware of except for OASv2 vs OASv3 support (see below).

> perhaps a brief rundown on what we do support and what we plan to support

I will add a note about OASv2 vs OASv3 support and the timeline for that.

> definitely need an example "how to" here

There's no "how to" for file validation that I can think of. On every change to the file, the validator simply does a check on the file contents to make sure it follows the spec. The user doesn't have to do anything apart from make their changes. Do you have some way in mind to illustrate that better? Or am I misunderstanding the goal of this article?

> explain how to make an easy/common error then explain how the file validator helps you resolve it

I can demonstrate how adding an extra property generates a warning and such.

**Comment by rossmcdonald** [comment]
@marbemac Updated. Can you take another look?

**Comment by marbemac** [comment]
Looks good, I just updated the proprietary callout html to Chris and my latest thought on how to layer some functionality into markdown while minimizing disruption (we'll present our ideas soon :).

**Comment by rossmcdonald** [comment]
Ah, I like it!

**Comment by rowa97** [comment]
just saw the gif comment at the top of the article, I'll go ahead and merge this

**Pull request merged**
